# Конфигурация источника данных (Data source)
hibernate.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://93.94.144.90:5434/project1
hibernate.connection.username=sauronpg
hibernate.connection.password=PGS735015055

# Конфигурация самого Hibernate
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=validate
hibernate.default_schema=public
hibernate.current_session_context_class=thread